28 implement refresh token
tsiguenz/ft_transcendence pull request #58
Opened 2023-05-04 07:51 UTC by tsiguenz

* To test this PR you can change the expired time in auth.service / createTokens.
* The access token can be a really low value (I test with 10s) to force the utilisation of the refresh token.
* if you find a better solution to the reload in the main.ts don't hesitate to let a comment

2023-05-05 09:03 UTC, gmorange42 requested changes
Nice !

2023-05-05 12:11 UTC, Crysicia commented on backend/src/auth/auth.service.ts
> +    return tokens;
Might be extracted in a function, you repeat the same 3 lines multiple times

2023-05-05 12:11 UTC, Crysicia commented on backend/src/auth/auth.service.ts
> +    return tokens;
Here

2023-05-05 12:11 UTC, Crysicia commented on backend/src/auth/auth.service.ts
> +    return tokens;
And here

2023-05-05 12:15 UTC, Crysicia commented
Nice work.
Does it work with WebSockets ?

2023-05-08 09:33 UTC, gmorange42 approved these changes
All looks good, GG.

2023-05-08 09:34 UTC, merged